;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-or-to-char
	continuous-num/++
	forward-or-to-char
	paredit-backward-kill-sexp
	paredit-semicolon
	))

(setq mc/cmds-to-run-once
      '(
	))
