;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-or-to-char
	bison-electric-close-brace
	bison-electric-colon
	bison-electric-greater-than
	bison-electric-open-brace
	bison-electric-percent
	bison-electric-pipe
	bison-electric-semicolon
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	continuous-downcase-word
	continuous-num/++
	continuous-upcase-word
	delete-region-unless-prefix
	forward-or-to-char
	forward-sexp
	insert-register
	markdown-exdent-or-delete
	org-beginning-of-line
	org-force-self-insert
	org-self-insert-command
	paredit-backward-kill-sexp
	paredit-backward-kill-word
	paredit-doublequote
	paredit-forward-delete
	paredit-forward-kill-word
	paredit-kill
	paredit-newline
	paredit-open-round
	paredit-semicolon
	slime-space
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	full-screen
	mouse-buffer-menu
	org-ctrl-c-ctrl-c
	save-buffer-enhanced
	string-rectangle
	wdired-finish-edit
	))
